/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function V1FinalTee0401(props) {
  const { nodes, materials } = useGLTF('/V1FinalTee0401.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials.Rib_1X1_319gsm_FRONT_40772} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials.Rib_1X1_319gsm_FRONT_40772} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials.Knit_Cotton_Back_FRONT_40781} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials.PT_FABRIC_FRONT_51882} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials.Knit_Cotton_Front_FRONT_40750} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials.PT_FABRIC_FRONT_51850} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials.PT_FABRIC_FRONT_145478} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials.Knit_Cotton_Right_Sleeve_FRONT_40789} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials.PT_FABRIC_FRONT_51866} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials.PT_FABRIC_FRONT_283201} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials.Knit_Cotton_Left_Sleeve_FRONT_40761} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials.PT_FABRIC_FRONT_192032} />
    </group>
  )
}

useGLTF.preload('/V1FinalTee0401.glb')
